SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES *PRICE) AS 'TOTAL_SALES'
FROM  BOOK A, AUTHOR B, (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') C
WHERE A.BOOK_ID=C.BOOK_ID AND A.AUTHOR_ID=B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;