SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN(SELECT A.ITEM_ID
                FROM ITEM_TREE A LEFT JOIN ITEM_TREE B ON A.ITEM_ID=B.PARENT_ITEM_ID
                WHERE B.PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID DESC

-- SELECT A.ITEM_ID
--                FROM ITEM_TREE A LEFT JOIN ITEM_TREE B ON A.ITEM_ID=B.PARENT_ITEM_ID
--                WHERE B.PARENT_ITEM_ID IS NULL