SELECT 	PRODUCT_CODE, PRICE* B.SA AS 'SALES'
FROM PRODUCT A,
    (SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS SA
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) B
WHERE A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE
