SELECT A.CAR_ID, B.CAR_TYPE,
       ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100,0)   AS 'FEE'
FROM (SELECT * 
     FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE IN ('세단','SUV') AND 
     CAR_ID NOT IN (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE DATE_FORMAT(START_DATE,'%Y-%m-%d')<='2022-11-30' AND
                     DATE_FORMAT(END_DATE,'%Y-%m-%d')>='2022-11-01'   ) ) A,
      CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
WHERE A.CAR_TYPE=B.CAR_TYPE AND DURATION_TYPE LIKE '%30일%'
      AND ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100,0) BETWEEN 500000 AND 2000000
ORDER BY B.CAR_TYPE DESC,A.CAR_ID