SELECT B.ANIMAL_ID,B.ANIMAL_TYPE,B.NAME
FROM (SELECT *
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE '%Intact%') AS A 
     JOIN 
     (SELECT *
      FROM ANIMAL_OUTS
     WHERE SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE'%Neutered%') AS B 
     ON A.ANIMAL_ID=B.ANIMAL_ID
ORDER BY  B.ANIMAL_ID
