SELECT YEAR(SALES_DATE) as YEAR,MONTH(SALES_DATE) as MONTH,GENDER,count(distinct(b.USER_ID)) AS USERS
FROM USER_INFO a join ONLINE_SALE b on a.USER_ID=b.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER