WITH SU AS (SELECT COUNT(*)
         FROM USER_INFO
         WHERE YEAR(JOINED)='2021'
         )

SELECT YEAR(A.SALES_DATE) AS 'YEAR', MONTH(A.SALES_DATE) AS 'MONTH',
    COUNT(DISTINCT A.USER_ID) AS 'PURCHASED_USERS', 
    ROUND(COUNT(DISTINCT A.USER_ID ) /(SELECT * FROM SU),1) AS 'PUCHASED_RATIO'
 FROM ONLINE_SALE A  JOIN 
    (SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED)='2021'
   -- GROUP BY YEAR(JOINED)
    ) B ON A.USER_ID=B.USER_ID
 GROUP BY YEAR(A.SALES_DATE),MONTH(A.SALES_DATE)
 ORDER BY YEAR(A.SALES_DATE),MONTH(A.SALES_DATE)




