 SELECT A.CAR_ID, 
 CASE WHEN 
        EXISTS (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE A.CAR_ID=B.CAR_ID AND START_DATE<='2022-10-16' and END_DATE>='2022-10-16'
        ) THEN '대여중'
ELSE '대여 가능' END AS 'AVAILABILITY'
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 GROUP BY A.CAR_ID
 ORDER BY A.CAR_ID DESC

-- SELECT *
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- where DATE_FORMAT(START_DATE,'%Y-%m-%d')<='2022-10-16' and DATE_FORMAT(END_DATE,'%Y-%m-%d')>='2022-10-16' 
-- GROUP BY CAR_ID
-- HAVING DATE_FORMAT(START_DATE,'%Y-%m-%d')<='2022-10-16' and DATE_FORMAT(END_DATE,'%Y-%m-%d')>='2022-10-16' 