SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
WHERE A.PRODUCT_ID=B.PRODUCT_ID AND DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID