SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=5
GROUP BY A.PRODUCT_ID, PRODUCT_NAME
ORDER BY SUM(PRICE*AMOUNT)  DESC, A.PRODUCT_ID