SELECT A.PRODUCT_ID,PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A JOIN FOOD_ORDER AS B ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE,"%Y-%m")="2022-05"
GROUP BY A.PRODUCT_ID,PRODUCT_NAME
ORDER BY TOTAL_SALES desc , A.PRODUCT_ID