with b as (
    SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE DATE_FORMAT(START_DATE,'%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE,'%Y-%m')<='2022-10'
               GROUP BY CAR_ID
               HAVING COUNT(CAR_ID)>=5
)

SELECT MONTH(START_DATE) AS MONTH,a.CAR_ID,COUNT(a.CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a join b
               
where  a.CAR_ID=b.CAR_ID and DATE_FORMAT(START_DATE,'%Y-%m') >= '2022-08' 
    AND DATE_FORMAT(START_DATE,'%Y-%m')<='2022-10'
   
GROUP BY MONTH(START_DATE),a.CAR_ID
HAVING COUNT(a.CAR_ID)>0
ORDER BY MONTH(START_DATE),a.CAR_ID DESC