SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (Y.MAX_SIZE-SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR_SUB,MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) AS Y
     ON YEAR(E.DIFFERENTIATION_DATE) =Y.YEAR_SUB
ORDER BY YEAR ,YEAR_DEV 


