SELECT SUM(SCORE)AS SCORE,C.EMP_NO,EMP_NAME,POSITION,EMAIL
FROM  HR_EMPLOYEES AS B JOIN HR_GRADE AS C ON B.EMP_NO=C.EMP_NO
WHERE YEAR=2022
GROUP BY C.EMP_NO,EMP_NAME,POSITION,EMAIL
HAVING SUM(SCORE) =(SELECT MAX(TOTAL_SCORE)
                    FROM ( SELECT SUM(SCORE) AS TOTAL_SCORE
                            FROM HR_GRADE
                            WHERE YEAR=2022
                            GROUP BY EMP_NO)AS SUBQUERY)
# ORDER BY